ARG ver_torchvision
ARG ver_pytorch
ARG cuda_tag

FROM nvidia/cuda:${cuda_tag}

ARG cuda_tag
RUN echo "building image based on nvidia/cuda:${cuda_tag}"

ARG ver_pytorch
RUN echo "version of pytorch: ${ver_pytorch}"
ARG ver_torchvision
RUN echo "version of torchvision: ${ver_torchvision}"

ARG uid
ARG gid

RUN groupadd -r -g ${gid} mpa && useradd -r -m mpa -s /bin/bash -g ${gid} -u ${uid} && echo "${gid}:${uid}"

ENV TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0+PTX"

# set work directory
WORKDIR /usr/src/app

# set environment variables
# to prevent generation of __pycache__ folders
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN apt-get update && \
    apt-get install -y build-essential curl libgtk-3-dev

COPY --from=openvino/ubuntu18_dev:2020.3 /opt/intel/openvino /opt/intel/openvino

RUN curl -o ~/miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
     chmod +x ~/miniconda.sh && \
     ~/miniconda.sh -b -p /opt/conda && \
     rm ~/miniconda.sh
ENV PATH /opt/conda/bin:$PATH

RUN conda install -y python=3.7 cython
RUN conda install -y pytorch=$ver_pytorch torchvision=$ver_torchvision -c pytorch && conda clean -ya

COPY ./requirements.txt .
ENV FORCE_CUDA="1"
RUN pip install --upgrade pip
RUN pip install -r ./requirements.txt

# install mmdetection
COPY ./external  /usr/src/app/external
RUN cd ./external/mmdetection/ && \
    pip install -r requirements/build.txt && \
    pip install -v -e . && \
    pip install -r requirements/runtime.txt && \
    cd -

# install mmsegmentation
RUN cd ./external/mmsegmentation/ && \
    pip install -r requirements.txt && \
    pip install -v -e . && \
    cd -

# install MDA
RUN cd ./external/mda/ && \
    pip install -v -e . && \
    cd -

# install HPO
RUN cd ./external/hpo/ && \
    pip install -v -e . && \
    cd -

RUN chown -R mpa:mpa /usr/src/app

USER mpa

RUN echo "source /opt/intel/openvino/bin/setupvars.sh" >> /home/mpa/.bash_profile
ENV BASH_ENV "/home/mpa/.bash_profile"
