ARG BASE
FROM ${BASE}

# install unittest dependencies
RUN mkdir /tmp/whl
WORKDIR /tmp/whl
COPY wheels/* /tmp/whl/

# RUN pip install --trusted-host pypi.sclab.intel.com --extra-index-url http://pypi.sclab.intel.com:8000 e2e-test-framework~=1.172.0
RUN pip install e2e_test_framework-1.172.20210519111305-py3-none-any.whl
RUN rm -rf /tmp/whl

RUN pip install pytest pytest-cov bandit flake8 mypy pylint coverage testfixtures
