_base_: [
    './train_multilabel.yaml',
    '../_base_/data/multicls_data.py',
    '../_base_/models/classifiers/classifier.py',
]

runner:
    max_epochs: 50

optimizer_config:
    type: SAMOptimizerHook

optimizer:
    type: SGD
    lr: 0.007
    momentum: 0.9
    weight_decay: 0.0005

evaluation:
    metric: ['accuracy', 'class_accuracy']

task_adapt:
    type: 'mpa'
    op: 'REPLACE'

custom_hooks:
- type: ModelEmaV2Hook
- type: LazyEarlyStoppingHook
  start: 0
  patience: 10
  iteration_patience: 0
  metric: 'mAP'
  interval: 1
  priority: 75

seed: 5
deterministic: True