_base_: [
    './train.yaml',
    '../_base_/data/supcon_data.py',
    '../_base_/models/cls_supcon.py',]

runner:
    max_epochs: 20

optimizer_config:
    type: SAMOptimizerHook

optimizer:
    type: SGD
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0005

# lr_config:
#     warmup: 'linear'
#     warmup_iters: 5
#     warmup_ratio: 0.01
#     warmup_by_epoch: true

# evaluation:
    # metric: ['accuracy', 'class_accuracy']

custom_hooks:
- type: NoBiasDecayHook
- type: ModelEmaV2Hook
