_base_: [
    './train.yaml',
    '../_base_/data/supcon_data.py',
    '../_base_/models/cls_supcon.py',]

runner:
    max_epochs: 100

optimizer_config:
    type: SAMOptimizerHook

optimizer:
    type: SGD
    lr: 0.2
    momentum: 0.9
    weight_decay: 0.0001

# evaluation:
    # metric: ['accuracy', 'class_accuracy']

# task_adapt:
#     type: 'mpa'
#     op: 'REPLACE'

custom_hooks:
- type: NoBiasDecayHook
- type: ModelEmaV2Hook
