_base_: [
    '../_base_/logs/tensorboard_logger.py',
    '../_base_/optimizers/sgd.py',
    '../_base_/runners/cls_runner.py',
    '../_base_/schedules/1cycle.py',
]

optimizer:
    lr: 0.007
    momentum: 0.9

runner:
    max_epochs: 60

evaluation:
    metric: ['accuracy']
