_base_: [
    '../_base_/logs/tensorboard_logger.py',
    '../_base_/optimizers/sgd.py',
    '../_base_/runners/epoch_runner.py',
    '../_base_/schedules/plateau_cls.py',
    #'../_base_/schedules/cos_anneal.py',
]

optimizer: 
    lr: 0.03
    momentum: 0.9

runner: 
    max_epochs: 10

evaluation: 
    metric: ['accuracy']
